image: node:16-alpine
pages:
  cache:
    paths:
      - node_modules/
  before_script:
    - apk add git
  script:
    - npm install
    - npm run docs:build
  artifacts:
    paths:
      - public
  only:
    - main
